### ISSUE TITLE
Make the app work without magnetometer

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/RaiseToAnswer#17]
Apparently this sensor is reasonably uncommon. We could support a lot more users if we could deal with it not being available.

**Comment by billthefarmer** [comment]
I have a original Moto G phone which doesn't have many sensors. The proximity detector seems to be the favourite for detecting phone to ear. The Phone app must use it. It triggers as about 1cm distance.There's a very old app called Sensor Readout on F-Droid, if you haven't already found it, which is good for finding out what does what.

**Comment by TheLastProject** [comment]
The problem with that is that this app also offers a feature to hang up calls by flipping your phone over. With just the proximity sensor you obviously can't differentiate between those.

**Comment by TheLastProject** [comment]
https://github.com/TheLastProject/RaiseToAnswer/commit/7acb12e436438e066f4e6c7b0a90715589c2cc71 reinstates the support for only the Raise To Answer feature. Because we can't reliably differentiate between holding against your ear or flipping over without magnetometer, flipping over is disabled on devices without magnetometer.
