### ISSUE TITLE
Auto-answer

### ISSUE THREAD

**Issue by yardenac** [TheLastProject/RaiseToAnswer#36]
I would like an option to answer phone calls automatically, on speakerphone, with zero user interaction. Would you be interested in offering this option, or accepting a PR for it?

**Comment by TheLastProject** [comment]
I'm not completely sure what the use of this would be. Because it answers based on proximity, you will have it near your ear when you answer. Sounds like a good way to hurt your ears by the volume difference if it would activate speakerphone?

**Comment by yardenac** [comment]
I want it to automatically answer _without_ needing any proximity.

A friend of mine is in a coma in the hospital. If it wasn't for covid, a lot of us would be there next to her. But since we can't, we want to keep a phone by her bed and be able to call it, so she can hear our voices.

This is a narrow use-case, but I'm sure there are others as well. If you don't want to offer this feature, I'll try and figure out how to host a fork on f-droid myself.

**Comment by TheLastProject** [comment]
I am so sorry about that, that must be awful. I really hope the best for her.

Regarding your feature request, I don't think it makes much sense to add this to Raise To Answer as it is so different from the rest of the app and would likely cause confusion to many users.

There is already an apps on F-Droid which claim to answer automatically by the way, it is called AutoAnswer. Have you tried that yet?

If AutoAnswer doesn't work, making Raise To Answer do what you want would mostly involve simply removing the sensor listener and calling the pickUp code on an incoming call. For publishing on F-Droid you could go the RFP route on 
https://gitlab.com/fdroid/rfp, which means you won't have to learn F-Droid yourself.

While I won't accept code for your feature in this app myself, I am willing to answer questions you may have about this codebase. Therefore, I will close this issue but feel free to ask more questions here anyway.

**Comment by yardenac** [comment]
Thanks for your help. AutoAnswer is many years out of date and doesn't work on any phone I've tried it with. I will let you know if I need help forking. :)

**Comment by Nickoriginal** [comment]
@yardenac what about [this](https://play.google.com/store/apps/details?id=me.yardenac.comaphone) app?

**Comment by yardenac** [comment]
Lol! I made that app myself as an experiment and I did a terrible job. I should probably delete it.
