### ISSUE TITLE
vibration and beeping not working in fallback code

### ISSUE THREAD

**Issue by Kyogre** [TheLastProject/RaiseToAnswer#50]
In RaiseToAnswer app I have option "beep sound" disabled and option "vibration" enabled, but when I answering call these two options reverts opposite, so I hear only beeps instead of hearing vibration. But the app says that I still have "beep sound" disabled and "vibration" enabled.

**Comment by TheLastProject** [comment]
I can't see anything in the code that would explain this behaviour, sadly :(

**Comment by Kyogre** [comment]
I have root access. Maybe that will help us collect needed logs?

**Comment by TheLastProject** [comment]
The problem is more than I have no clue what kind of logs could possibly explain this better :(

**Comment by Kyogre** [comment]
[logcat_06-18-2021_22-05-55.txt](https://github.com/TheLastProject/RaiseToAnswer/files/6680368/logcat_06-18-2021_22-05-55.txt)
Here is logcat logs attached. I see at least two "permission denial" messages in these logs.
I suggest to compare my logs with normal device logs, maybe that will help to investigate my problem and maybe even other problems.

**Comment by TheLastProject** [comment]
I may have fixed this in 681adeb3d995539e2b44bf702dda008ce20c5f54 (if I did, I understood your issue wrongly and the options didn't "revert" they were just ignored for devices without magnetometer).

Please try release 3.6.2: https://github.com/TheLastProject/RaiseToAnswer/releases/tag/v3.6.2

**Comment by Kyogre** [comment]
Yeah, 3.6.2 did the job. Vibration now works fine. Thank you, you can close the issue.

**Comment by TheLastProject** [comment]
Thanks for confirming!
