### ISSUE TITLE
about hackerchick.me

### ISSUE THREAD

**Issue by ghost** [TheLastProject/RaiseToAnswer#98]
@TheLastProject 
* hackerchick.me source_ https://gitlab.com/fdroid/fdroiddata/-/blame/master/metadata/me.hackerchick.raisetoanswer.yml#L6
* web browsers complain about expired [ almost 2 years old ] ca cert
  * did you forgot to stop redirecting to https://sylviavanos.nl
  * else, please update ca cert

**Comment by TheLastProject** [comment]
I'd rather have it redirect to sylviavanos.nl. Probably best to update the F-Droid metadata for my apps to point the author website to sylviavanos.nl instead :)

Thanks for noticing this! I'll try to find some time to look at the cert soon (but please just use sylviavanos.nl as url to share)
