### ISSUE TITLE
Merge ComaPhone into RaiseToAnswer

### ISSUE THREAD

**Issue by GreenLunar** [TheLastProject/RaiseToAnswer#99]
Merge into one https://github.com/yardenac/comaphone/issues/1

**Comment by TheLastProject** [comment]
I explicitly suggested for them to make their own app because the features they wanted were so different from the purpose of Raise To Answer.

So no, not planning this and not interested in this, sorry.

**Comment by GreenLunar** [comment]
Auto-answer is a useful feature.

The number of features, of both programs, is not immense, so I urge you
to think this over.

Auto-answer is a useful feature; especially today when machine learning
is widely available.

## Here's a use case

You place a computer activated (an SBC for that matter) to record
audible activity in your office when you are away.

At the same time, you also leave your telephone device in your office.

The computer will recognize various of voices and will recognize that
someone has called you and left a message (if the computer is trained
to sound a "Hello, I'm out of town, please leave a message" upon
device ring).

Shortly after, you get an email with a recorded voicemail.

## Why does this use-case matter?

Here are reasons to understand how crucial this is:

Because, we know that the couple of companies that design the systems
used for telephony-incorporated-PDAs want us to be with that tracking
device 24/7.

They don't want us:

* detached from these devices (They say "DON'T MISS OUT!")
* to record our calls.
* to have control nor ownership over information.
* to have trie control over telecommunication.

Even postmarketOS can't record calls (currently only PinePhone devices
can make audio recordings) because it needs drivers for modem too in
order to further this cause.

Having a program that gives us abilities to further the idea of
auto-answer, and consequently answering machine, would make wonders.

Please reconsider.

See also: https://wiki.postmarketos.org/wiki/Answering_Machine

@yardenac
